implement props for styles in header
it-academyproject/ita-directory pull request #262
Opened 2021-09-29 11:09 UTC by sinfreno

2021-09-29 11:21 UTC, kevinmamaqi requested changes

2021-09-29 11:21 UTC, kevinmamaqi commented on frontend/src/components/layout/Header/Header.styles.js
> +			font-weight: 100;
El font-weight mejor que sea normal. 100 es muy fino y apenas ofrece contraste. Si lo has visto así en el diseño de Adobe XD, dime donde para corregirlo.

2021-09-29 11:21 UTC, kevinmamaqi commented on frontend/src/screens/MyBills/MyBills.js
> +			color_header="#e6f2f2"
Los colores que esten tipeados a través de la variable Colors y/o de los estilos de Tailwind.css

2021-09-29 11:21 UTC, kevinmamaqi commented on frontend/src/components/layout/Header/Header.js
> +			color_header={color_header}
Mejor todo camelCase: colorHeader / colorLetra, etc... 

Y todavía mejor en ingles: fontColor, headerColor, etc...

2021-09-30 15:52 UTC, kevinmamaqi commented
Revisa los cambios @sinfreno

2021-10-04 08:53 UTC, kevinmamaqi commented
Hola @maze02 te asigno la tarea, revisa conflictos y comentarios

2021-10-04 10:56 UTC, merged

2021-10-04 15:40 UTC, maze02 commented on frontend/src/components/layout/Header/Header.js
> +			color_header={color_header}
Implementado

2021-10-04 15:40 UTC, maze02 commented on frontend/src/components/layout/Header/Header.styles.js
> +			font-weight: 100;
Implementado