415 create 404 not found page
it-academyproject/ita-directory pull request #416
Opened 2021-12-16 09:14 UTC by padreno

#415 create page error 404 with two buttons to back to login page and the other to "contact us" in a case of any issue. This last button doesn't route to any contact form !

2021-12-16 11:15 UTC, kevinmamaqi requested changes
@padreno sobretodo quita todos los styled components que has creado, no son necesarios y hay que reutilizar más.

2021-12-16 11:15 UTC, kevinmamaqi commented on frontend/src/screens/NotFound/NotFound.js
> +			<HttpMess>404</HttpMess>
Casi todos los styled components de aquí son redundantes, deberían de ser más genéricos para reutilizarse. Por ejemplo <HttpMess> debería de ser un H1.

2022-01-10 08:01 UTC, kevinmamaqi commented
@padreno  pull-request debe ir contra develop, no main.

2022-01-11 08:02 UTC, kevinmamaqi requested changes

2022-01-11 08:02 UTC, kevinmamaqi commented on .vscode/settings.json
> -    "editor.defaultFormatter": "esbenp.prettier-vscode"
Obligatorio usar prettier.

2022-01-13 08:14 UTC, kevinmamaqi requested changes

2022-01-13 08:14 UTC, kevinmamaqi commented on frontend/src/screens/NotFound/NotFound.js
> +			<h1 className="http__Message">404</h1>
utilizar BEM o css al uso lowercase con guión

2022-01-13 09:41 UTC, padreno commented on frontend/src/screens/NotFound/NotFound.js
> +			<h1 className="http__Message">404</h1>
he cambiado los nombres de classes

2022-01-24 08:16 UTC, closed without merging