update users.controller para el recovery-password a traves del envio d…
it-academyproject/ita-directory pull request #443
Opened 2022-01-26 12:53 UTC by vicb-rf

implement recovery  password #346

2022-01-27 08:05 UTC, kevinmamaqi requested changes

2022-01-27 08:05 UTC, kevinmamaqi commented on backend/app/controllers/users.controller.js
> +		const passUser = await prisma.user.findUnique({where: {email}});
Llámalo user

2022-01-27 08:05 UTC, kevinmamaqi commented on backend/app/controllers/users.controller.js
> +				to: email,
Solo cambia el email de destinatario, y se podría centralizar

2022-01-28 09:44 UTC, vicb-rf commented on backend/app/controllers/users.controller.js
> +				to: email,
He actualizado el envio de email.

2022-01-31 08:01 UTC, kevinmamaqi approved these changes

2022-01-31 08:01 UTC, merged