515 implement and test change password
it-academyproject/ita-directory pull request #522
Opened 2022-03-18 07:12 UTC by mariano-farace

Now when a password reset is requested, the user won't be allowed to choose an old, or repeated password.

2022-03-18 07:16 UTC, mariano-farace commented
+18,095 −87 lineas?? Es esperable cuando haces una migracion? O la hice mal?

2022-04-01 07:08 UTC, kevinmamaqi commented
@mariano-farace revisa los conflictos please. Cambiaron algunos archivos.

2022-04-03 18:15 UTC, mariano-farace commented
@kevinmamaqi Hecho! No mas conflictos

2022-04-05 07:05 UTC, kevinmamaqi requested changes
@mariano-farace en la carpeta prisma/node_modules no debería de haber node_modules y además no debería de compartirse ninguna carpeta de node_modules en git.

2022-04-06 04:24 UTC, mariano-farace commented
No me habia dado cuenta. Entiendo que esta resuelto

2022-04-06 07:06 UTC, kevinmamaqi approved these changes

2022-04-06 07:06 UTC, merged