logger working on ads routes & handler-errors
it-academyproject/ita-directory pull request #538
Opened 2022-04-15 09:20 UTC by xaviercomi

The middleware handler-logger works on all /ads/ routes. It uses the implement function apiResponse to show the responses from controllers on console. Also creates a file .log on folder /pino-logger if not exist where stocks all the generated log's

2022-04-19 08:03 UTC, kevinmamaqi requested changes

2022-04-19 08:03 UTC, kevinmamaqi commented on backend/app/middleware/handler-logger.js
> +const ipily = require('ipily')
Quitar `ipily()`.

2022-04-19 08:03 UTC, kevinmamaqi commented on backend/app/middleware/handler-logger.js
> +const geoip = require('fast-geoip');
Quitar geoip()

2022-04-19 08:03 UTC, kevinmamaqi commented on backend/app/middleware/handler-logger.js
> +const ip = require('ip');
quitar `ip` package.

2022-04-19 08:03 UTC, kevinmamaqi commented on backend/app/middleware/handler-logger.js
> +async function handlerLogger(req, res, next) {
Obten IP, información necesaria, etc... del request de Express.

2022-04-20 07:21 UTC, kevinmamaqi requested changes

2022-04-20 07:21 UTC, kevinmamaqi commented on backend/server.js
> +	logger.warn(`Visit: http://localhost:${process.env.PORT}/`);
Quitar warn, debería info

2022-04-20 07:21 UTC, kevinmamaqi commented on backend/prisma/schema.prisma
> -model level {
Revisar porque se ha borrado.

2022-04-20 07:21 UTC, kevinmamaqi commented on backend/pino-loger/server.log
> +{"level":30,"time":1650217614363,"pid":17912,"hostname":"MSI","msg":"Server is running on port and working 10910."}
Añadir en .gitignore el archivo, para que lo ignore

2022-04-20 07:21 UTC, kevinmamaqi commented on backend/app/utils/utils.js
> +const logger = require("../../pino-loger/logger");
nombrar archivos con camelCase. handleErrors o handleLogger

2022-04-20 07:21 UTC, kevinmamaqi commented on backend/app/middleware/handler-errors.js
> +	logger.fatal({code, header, message})
Cambiar a logger.error

2022-04-20 08:17 UTC, xaviercomi commented on backend/app/middleware/handler-logger.js
> +const {detect} = require('detect-browser');
Ahora he visto porque lo utilizaba detect-browser. user-agent devuelve:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
sin importar que navegador utilices.

2022-04-20 08:57 UTC, xaviercomi commented on backend/app/middleware/handler-logger.js
> +const {detect} = require('detect-browser');
Si, si quiero decir puedes detectarlo utilizando user-agent, pero o lo implementas de forma manual como el ejemplo que me envías, o también utilizando una API como esta: https://developers.whatismybrowser.com/useragents/parse/#parse-useragent
O también con una librería como detect-browser u otra. La librería me pareció que era la más rápida de implementar y dejaba el código más limpio, pero si hace falta lo hago con funciones o un switch o condicionales.

2022-04-20 09:03 UTC, xaviercomi commented on backend/prisma/schema.prisma
> -model level {
Esto yo creo que era alguna modificación que dejo estas líneas de código sin borrar. El model level y level_type están en las líneas 117 y 129 bien definidas. Es código sucio que se debe de haber quedado en algún corta-pega diria.

2022-04-20 09:04 UTC, xaviercomi commented
Lo subo para ir quitando cosas

2022-04-20 09:05 UTC, kevinmamaqi commented on backend/app/middleware/handler-logger.js
> +const {detect} = require('detect-browser');
No necesitas ninguna librería, debes guardar información fidedigna al request original por dos motivos:
- Performance.
- En el futuro tener acceso a los datos originales. Imaginate que la libreria detect-browser tiene un bug que arreglan en un mes, y no tienes los datos originales.

2022-04-21 07:59 UTC, xaviercomi commented
Acabo de subir la modificacion al handlerLogger para que pida el user agent y muestre la informacion del navegador, version, etc.

2022-04-21 08:01 UTC, kevinmamaqi approved these changes

2022-04-21 08:01 UTC, merged