555 refactor register login
it-academyproject/ita-directory pull request #559
Opened 2022-04-28 14:13 UTC by monicab1989

2022-04-28 14:29 UTC, kevinmamaqi requested changes

2022-04-28 14:29 UTC, kevinmamaqi commented on frontend/src/components/atoms/Forms/ErrorMessage.jsx
> +const ErrorStyled = styled.p`
Aquí usaria el componente Text con el parametro as="span"

2022-04-28 14:29 UTC, kevinmamaqi commented on frontend/src/components/atoms/Forms/ErrorMessage.jsx
> +  color: red;
Utiliza una referencia a los colores definidos en `theme/colors`

2022-04-28 14:29 UTC, kevinmamaqi commented on frontend/src/components/atoms/Forms/Input.jsx
> +import { InputStyled } from './Input.styled'
Elimina el archivo Input.styled y trae los estilos al componente

2022-04-28 14:29 UTC, kevinmamaqi commented on frontend/src/components/atoms/Forms/Input.styled.js
> +  border-radius: 0.5rem;
border-radius esta repetido

2022-04-28 14:29 UTC, kevinmamaqi commented on frontend/src/components/molecules/InputGroup.jsx
> +  console.log(error)
Elimina el console.log(), es más ¿No te sale un warning que no te deja pasar el git commit?

2022-04-28 14:49 UTC, monicab1989 commented on frontend/src/components/atoms/Forms/Input.styled.js
> +  width: 90%;
He corregido todo lo que me has puesto excepto esto, porque si lo quito el input queda más pequeño y se queda en la mitad más o menos

2022-04-28 15:34 UTC, monicab1989 commented on frontend/src/components/molecules/InputGroup.jsx
> +  console.log(error)
Al final me voy a quedar mejorando esto porque no se porque no funciona el acceso cuando eso no se está manipulando....así que voy a ver donde puede estar el error

2022-04-29 09:31 UTC, kevinmamaqi approved these changes

2022-04-29 09:31 UTC, merged

2022-04-29 09:51 UTC, monicab1989 commented on frontend/src/components/atoms/Forms/ErrorMessage.jsx
> +import colors from '../../../theme/Colors'
Si ahora modifico eso pero todavía no lo apruebes porque las notificaciones no saltan al dar el botón creo que el error está en que no se pasa bien la referencia del input al inputgroup, pero todavía no se solucionarlo me dice que utilice React. forwardRef, entonces tengo que ver como podría arreglarlo.

2022-05-01 11:17 UTC, monicab1989 commented on frontend/src/components/atoms/Forms/ErrorMessage.jsx
> +import colors from '../../../theme/Colors'
Vale ya esta todo arreglado y solucionado