565 refactor atoms
it-academyproject/ita-directory pull request #572
Opened 2022-05-02 18:10 UTC by monicab1989

#565

2022-05-02 20:10 UTC, kevinmamaqi requested changes

2022-05-02 20:10 UTC, kevinmamaqi commented on frontend/src/components/atoms/Forms/Input.jsx
> +      {icon && <FontAwesomeIcon icon={icon} />}
Elimina el icono del componente, que solo contenga el propio componente.

2022-05-02 20:10 UTC, kevinmamaqi commented on frontend/src/components/atoms/Forms/TextArea.jsx
>          <TextAreaInput
Este componente solo debería de ser el TextAreaInput, el resto son el label y el ErrorMessage del resto de componentes.

2022-05-02 20:10 UTC, kevinmamaqi commented on frontend/src/components/layout/Body/Body.jsx
> +  isLoggedIn: PropTypes.oneOfType([PropTypes.string, PropTypes.bool]),
Debería de ser booleano

2022-05-02 20:10 UTC, kevinmamaqi commented on frontend/src/components/layout/Header/Header.jsx
> +  isLoggedIn: PropTypes.oneOfType([PropTypes.string, PropTypes.bool]),
Debería de ser booleano

2022-05-02 20:10 UTC, kevinmamaqi commented on frontend/src/components/organisms/ContactModal/ContactModal.jsx
> +import Button from '../../atoms/Forms/Button'
Esto debería de improtarse desde Atoms directamente, no desde atoms/Forms/Button

2022-05-03 09:27 UTC, monicab1989 commented on frontend/src/components/organisms/ContactModal/ContactModal.jsx
> +import Button from '../../atoms/Forms/Button'
Ya he quitado el icono del input, creado un textAreaGroup, y quitado del textArea el error y el label. Sacado el button del forms y puesto en atoms, y dejado como antes el tipo de la variable isloggedIn

2022-05-03 09:27 UTC, kevinmamaqi commented
@monicab1989 fijate en los conflictos please

2022-05-03 10:48 UTC, kevinmamaqi approved these changes

2022-05-03 10:48 UTC, merged