Create card component, change the Card for cardOrganism
it-academyproject/ita-directory pull request #590
Opened 2022-05-04 18:50 UTC by monicab1989

#576

2022-05-04 18:50 UTC, monicab1989 commented
Al final lo he hecho así...a ver que te parece...

2022-05-04 19:09 UTC, kevinmamaqi requested changes

2022-05-04 19:09 UTC, kevinmamaqi commented on frontend/src/components/organisms/Card/CardOrganism.jsx
> +        <p>{text}</p>
`<Text />`

2022-05-04 19:09 UTC, kevinmamaqi commented on frontend/src/components/organisms/Card/CardOrganism.jsx
> +        <h3>{title}</h3>
`<Title />`

2022-05-04 19:09 UTC, kevinmamaqi commented on frontend/src/components/organisms/Card/CardOrganism.jsx
> +function CardOrganism({ image, title, description, text, footer, name }) {
Este componente sobra

2022-05-04 19:09 UTC, kevinmamaqi commented on frontend/src/pages/UserAds/AdCard/AdCard.jsx
> +import CardOrganism from '../../../components/organisms/Card/CardOrganism'
Este componente sobra, o quizas necesite otro nombre.

2022-05-05 07:06 UTC, kevinmamaqi requested changes

2022-05-05 07:06 UTC, kevinmamaqi commented on frontend/src/components/organisms/Card/CardAd.jsx
> +  h3 {
${Title}

2022-05-05 07:06 UTC, kevinmamaqi commented on frontend/src/components/organisms/Card/CardAd.jsx
> +  p {
`${Text}`

2022-05-05 07:06 UTC, kevinmamaqi commented on frontend/src/components/organisms/Card/CardAd.jsx
> +      <Img src={`${import.meta.env.REACT_APP_STATIC_FILES_URL}/${image}`} alt={name} />
Las variables de entorno de Front han de comenzar con VITE_, fijate:  `REACT_APP_STATIC_FILES_URL `

2022-05-05 07:06 UTC, kevinmamaqi commented on frontend/src/pages/UserAds/AdCard/AdCard.jsx
> +  containerClassName: PropTypes.oneOfType([PropTypes.string, PropTypes.object]),
Esto no puede ser un objeto.

2022-05-05 16:06 UTC, kevinmamaqi approved these changes

2022-05-05 16:06 UTC, merged